<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Kwiki Sweepstakes Website | Design By Developer Bazaar Technology</title>

    <!-- site favicon -->

    <link rel="shortcut icon" type="image/png" href="assets/images/favicon.png">

    <!-- main style css link -->

    <link rel="stylesheet" href="assets/css/style.css">

    <!-- responsive css link -->

    <link rel="stylesheet" href="assets/css/responsive.css">

    <!-- Twitter Meta Property Started -->

    <meta property="twitter:image" content="assets/images/favicon.png" />

    <meta property="twitter:image:width" content="350" />

    <meta property="twitter:image:height" content="597" />

    <meta name="twitter:domain" content="Kwiki Sweepstakes" />

</head>

<body>

    <!--  header-section start  -->

    <?php include('assets/include/header.php'); ?>

    <!--  header-section end  -->

    <!-- privacy-policy-section start -->

    <section class="section-padding static-page">

        <div class="container">

            <div class="row">

                <div class="col-lg-12 col-md-12 col-sm-12 col-xl-12">

                    <h3 class="mb-3">Terms of Service</h3>
                    <p>KWIKISWEEPS, Inc. a Delaware Corporation (<strong>Company, we, us, or our</strong>) provides its services (described below) to you through its website located at www.kwikisweeps.com (the <strong>Site</strong>, and together with such services, including any new features, the <strong>Services</strong>, subject to the following Terms of Service (as amended from time to time, the <strong>Terms of Service</strong>.We reserve the right, at our sole discretion, to change or modify portions of these Terms of Service, including the cost of the Services, at any time.If we do this, we will post the changes on this page and will indicate at the top of this page the date these terms were last revised. We will also notify you, either through the Services user interface, in an email notification (if an email address is provided by you) or through other reasonable means. Your continued use of the Services after the date any such changes become effective constitutes your acceptance of the new Terms of Service. If you are under 18 years of age or the age of majority in your jurisdiction of residence, you are not authorized to use the Services.The Services may only be used by individuals for personal, non-commercial use; commercial enterprises and business entities are not eligible to access and use the Services. </p>
                    <p>THESE TERMS OF SERVICE ARE ENTERED INTO BY AND BETWEEN YOU (<strong>YOU</strong>, <strong>YOUR</strong> AND COMPANY, AND GOVERN YOUR USE OF THE SERVICES.BY USING THE SERVICES OR OTHERWISE INDICATING YOUR ACCEPTANCE OF THESE TERMS OF SERVICE (THE EARLIEST OF WHICH IS REFERRED TO HEREIN AS THE <strong>ACCEPTANCE DATE</strong>, INCLUDING BY CLICKING I AGREE/ACCEPT, YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT YOU HAVE READ THESE TERMS OF SERVICE, ARE BOUND BY THESE TERMS OF SERVICE, AND HEREBY AGREE TO THE TERMS AND CONDITIONS SET FORTH HEREIN.IF YOU DO NOT ACCEPT ALL THE TERMS AND CONDITIONS OF THESE TERMS OF SERVICE, YOU MAY NOT USE THE SERVICES.</p>
                    <p><em><strong>PLEASE READ THESE TERMS OF SERVICE CAREFULLY, AS THEY CONTAIN AN AGREEMENT TO ARBITRATE AND OTHER IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES, AND OBLIGATIONS.TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE AGREEMENT TO ARBITRATE REQUIRES (WITH LIMITED EXCEPTION) THAT YOU SUBMIT CLAIMS YOU HAVE AGAINST US TO BINDING AND FINAL ARBITRATION, AND FURTHER (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST COMPANY ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, (2) YOU WILL ONLY BE PERMITTED TO SEEK RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ON AN INDIVIDUAL BASIS, AND (3) YOU MAY NOT BE ABLE TO HAVE ANY CLAIMS YOU HAVE AGAINST US RESOLVED BY A JURY OR IN A COURT OF LAW.</strong></em></p>
                    <p>In addition, when using certain services, you will be subject to any additional terms applicable to such services that may be posted on the Services (the <strong>Additional Terms</strong> from time to time, including, without limitation, the Privacy Policy located at <a href="http://www.wizza.com/">www.kwikisweeps.com</a> (the <strong>Privacy Policy</strong> and the Official Rules (as defined below) located at <a href="https://wizza.com/howitworks">https://kwikisweeps.com/howitworks</a>. All such terms are hereby incorporated by reference into these Terms of Service.</p>
                    <h3 class="mb-3">Access and Use of the Services</h3>
                    <p><strong>Services Description:</strong>The Services are designed to facilitate entry into, and administration of, sweepstakes (i.e., promotional contests) sponsored by the Company (each, a <strong>Sweepstakes</strong>. Participation
                        in Sweepstakes will be subject to separate terms and conditions governing participation in the Sweepstakes (the <strong>Official Rules</strong>.<strong><u>For details on how to enter a Sweepstakes, eligibility, the prize description, information about prize delivery and other matters relating to the administration of the Sweepstakes visit the Official Rules</u></strong>.
                        By entering into any Sweepstakes you hereby acknowledge that you have read and agree to be bound the Official Rules governing such Sweepstakes.No purchase, payment or other financial contribution is necessary to enter or win a Sweepstakes. SWEEPSTAKES ARE VOID WHERE PROHIBITED OR RESTRICTED BY LAW.</p>
                    <p><strong>Account</strong>: In order to access certain features of the Services, you may be required to create an account (<strong>Account</strong>. In registering an Account, please provide true, accurate, current and complete information about yourself as prompted by the registration form (<strong>Registration Data</strong> and maintain and promptly update the Registration Data accordingly. You represent that you are at least 18 years old or the age of majority in your jurisdiction of residence, legally capable of entering into a contract, and not a person barred from using the Services under the laws of the United States, your jurisdiction of residence or any other applicable jurisdiction. You are responsible for all activities that occur under your Account. You represent that you are not barred from using the Services under any applicable law and that you will be responsible for all activities that occur under your Account. You agree that you will monitor your Account to restrict its use by minors and other unauthorized users, will not share your Account or password with anyone, and will exit from your Account at the end of each session.
                        You further agree to notify Company immediately of any use of your password without your permission or authority or any other breach of the security of your Account. You agree not to create an Account using a false identity or
                        alias or if you previously have been banned from using any of the Services. You further agree that you will not maintain more than one Account for the same Company service at any given time. Company reserves the right to remove
                        or reclaim any usernames at any time and for any reason.</p>
                    <p><strong>News Updates: </strong>By using the Services, Company may request your affirmative consent in order to provide promotional emails or offers via a periodic email newsletter. Such promotional email newsletters will be completely
                        optional. You are not required to keep your subscription to such promotional email newsletters in order to be eligible to use the Services.You may subsequently opt-out of receiving such promotional email newsletters at any time by clicking the unsubscribe link in the newsletter and following the procedures set forth at such link.Please refer to our Privacy Policy for further information.</p>
                    <p><strong>Modifications to Services: </strong>Company reserves the right to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice. You agree that Company will not be liable to you
                        or to any third party for any modification, suspension or discontinuance of the Services.</p>
                    <p><strong>General Practices Regarding Use and Storage</strong>: You acknowledge that Company may establish general practices and limits concerning use of the Services, including without limitation the maximum period of time that data
                        or other content will be retained by the Services and the maximum storage space that will be allotted on Companys servers on your behalf. You agree that Company has no responsibility or liability for the deletion or failure to store any data or other content maintained or uploaded by the Services. You further acknowledge that Company reserves the right to change these general practices and limits at any time, in its sole discretion, with or without notice.</p>
                    <p><strong> </strong></p>
                    <h3 class="mb-3">Payments </h3>
                    <p>ALL ENTRIES, ONCE PAID, ARE NON-REFUNDABLE.</p>
                    <p>WE DO NOT PROCESS PAYMENTS. To facilitate payment of your paid entries into a Sweepstakes, we use third-party payment processors (collectively, <strong>Payment Processors</strong>. These payment processing services are provided by
                        the Payment Processors and are subject to the applicable Payment Processors terms and conditions, privacy policy, and all other relevant agreements (collectively, the <strong>Payment Processor Agreements</strong>. By agreeing to these Terms, users that use the payment functions of the Services also agree to be bound by the applicable Payment Processor Agreement for the payment function the user is using, as the same may be modified by the applicable Payment Processor from time to time. As a condition of Company enabling payment processing services through the Payment Processors, you represent and warrant to Company that all information you provide about your payment instruments and/or bank accounts is true and that you are authorized to use such payment instrument and/or bank account, as applicable. You also authorize Company to share transaction information related to your payment for the Services with the Payment Processors. You will promptly update your payment information with any changes (for example, a change in your billing address or credit card expiration date) that may occur. You hereby authorize the applicable Payment Processor to store and continue billing your specified payment method even after such payment method has expired, to avoid interruptions in payment for your use of the Services. Please contact the applicable Payment Processor for more information. Company assumes no liability or responsibility for any payments you make through the Services.</p>
                    <h3 class="mb-3">Conditions of Use</h3>
                    <p><strong>User Conduct: </strong>You agree not to: (a) take any action that imposes an unreasonable load on the Sites infrastructure, (b) use any device, software or routine to interfere or attempt to interfere with the proper working
                        of the Site or any activity being conducted on the Site, (c) attempt to decipher, decompile, disassemble or reverse engineer any of the software comprising or making up the Site, (d) modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Services or the Service Content (as defined below), in whole or in part, (e) delete or alter any material posted on the Site by Company or any other person or entity, (f) frame or link to any of the materials or information available on the Site, (g) engage in data mining or scraping or use robots, spiders, scripts, services, software or any manual or automatic device, tool, or process designed to data mine or scrape Service Content, data or information from the Site, or otherwise access or collect Service Content, data or information from the Site using automated means, or (h) engage in or use any data mining, robots, spiders, scraping or similar data gathering or extraction methods. If you are blocked by Company from accessing the Services (including by blocking your IP address), you agree not to implement any measures to circumvent such blocking (e.g., by masking your IP address or using a proxy IP address).Any use of the Services or the Service Content other than as specifically authorized herein is strictly prohibited. </p>
                    <p><strong>Compliance with Applicable Law:</strong> This Site is based in the United States.Company makes no claims concerning whether the Service Content may be downloaded, viewed, or if it is appropriate for use outside of the United
                        States.If you access the Site or the Service Content from outside of the United States, you do so at your own risk. Whether inside or outside of the United States, you are solely responsible for ensuring compliance with the laws of your specific jurisdiction.The United States controls the export of products and information. You expressly agree to comply with such restrictions and not to export or re-export any of the Service Content to countries or persons prohibited under the export control laws. By downloading the Service Content, you are expressly agreeing that you are not in a country where such export is prohibited or are a person or entity for which such export is prohibited. You are solely responsible for compliance with the laws of your specific jurisdiction regarding the import, export, or re-export of the Service Content.</p>
                    <p> <strong>Commercial Use: </strong>Unless otherwise expressly authorized herein or in the Services, you agree not to display, distribute, license, perform, publish, reproduce, duplicate, copy, create derivative works from, modify, sell,
                        resell, exploit, transfer or upload for any commercial purposes, any portion of the Services, use of the Services, or access to the Services.</p>
                    <p><strong>U.S. Government Restricted Rights</strong>. The Service Content is provided with RESTRICTED RIGHTS. Use, duplication, or disclosure by the U.S. government is subject to the restrictions contained in 48 CFR 52.227-19 and 48
                        CFR 252.227-7013 et seq. or its successor. Use of the Site or Service Content by the U.S. government constitutes acknowledgement of our proprietary rights in the Site and Service Content.</p>
                    <h3 class="mb-3">Intellectual Property Rights</h3>
                    <p><strong>Service Content: </strong>You acknowledge and agree that the Services may contain content or features (<strong>Service Content</strong> that are protected by copyright, patent, trademark, trade secret, or other proprietary
                        rights and laws. Except as expressly authorized by Company, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute, reproduce, retransmit or create derivative works based on the Services or the Service Content, in whole or in part, except that the foregoing does not apply to your own User Content (as defined below) that you upload to or make available through the Services in accordance with these Terms of Service. Any use of
                        the Services or the Service Content other than as specifically authorized herein is strictly prohibited.</p>
                    <p><strong>Trademarks:</strong> The Company name and logos are trademarks and service marks of Company (collectively the <strong>Company Trademarks</strong>. Other company, product, and service names and logos used and displayed via the
                        Services may be trademarks or service marks of their respective owners who may or may not endorse or be affiliated with or connected to Company. Nothing in these Terms of Service or the Services should be construed as granting,
                        by implication, estoppel, or otherwise, any license or right to use any of Company Trademarks displayed on the Services, without our prior written permission in each instance. All goodwill generated from the use of Company Trademarks will inure to our exclusive benefit.</p>
                    <p><strong>Third-Party Material: </strong>Under no circumstances will Company be liable in any way for any content or materials of any third parties (including users), including for any errors or omissions in any content, or for any loss
                        or damage of any kind incurred as a result of the use of any such content. You acknowledge that Company does not pre-screen content, but that Company and its designees will have the right (but not the obligation) in their sole
                        discretion to refuse or remove any content that is available via the Services. Without limiting the foregoing, Company and its designees will have the right to remove any content that violates these Terms of Service or is deemed by Company, in its sole discretion, to be otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any content, including any reliance on the accuracy, completeness, or usefulness
                        of such content.</p>
                    <p><strong>User Content: </strong>You represent and warrant that you own all right, title and interest, including all copyrights and rights of privacy and publicity contained therein, in and to any content or materials that you make available to Company, including by uploading, posting, publishing, or displaying via the Services or by emailing or otherwise making available to other users of the Services (collectively, <strong>User Content</strong>. You hereby grant Company and its affiliated companies, successors, and assigns a non-exclusive, worldwide, royalty-free, fully paid-up, transferable, sub-licensable (directly and indirectly through multiple tiers), perpetual, and irrevocable license to copy, display, upload, perform, distribute, store, modify, and otherwise use your User Content in connection with the operation of the Services and waive in favor of Company any so-called moral rights associated with such User Content. You assume all risk associated with your User Content and the transmission of your User Content, and you have sole responsibility for the accuracy, quality, legality and appropriateness of your User Content.</p>
                    <p>You hereby authorize Company and its third-party service providers to derive statistical and usage data relating to your use of the Services (<strong>Usage Data</strong>. We may use Usage Data for any purpose in accordance with applicable
                        law and our Privacy Policy.</p>
                    <p>Any questions, comments, suggestions, ideas, feedback, reviews, or other information about the Services <strong>Submissions</strong>, provided by you to Company are non-confidential and Company will be entitled to the unrestricted
                        use and dissemination of these Submissions for any purpose, commercial or otherwise, without acknowledgment, attribution, or compensation to you.</p>
                    <p>You acknowledge and agree that Company may preserve User Content and may also disclose User Content if required to do so by law or in the good faith belief that such preservation or disclosure is reasonably necessary to: (a) comply
                        with legal process, applicable laws, or government requests; (b) enforce these Terms of Service and Additional Terms; (c) respond to claims that any content violates the rights of third parties; or (d) protect the rights, property, or personal safety of Company, its users, or the public. You understand that the technical processing and transmission of the Services, including your User Content, may involve (i) transmissions over various networks; and (ii) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
                    <h3 class="mb-3">Third Party Websites</h3>
                    <p>The Services may provide links or other access to services, sites, technology, and resources that are provided or otherwise made available by third parties (the <strong>Third-Party Services</strong>. Additionally, you may enable or
                        log in to the Services via various online Third-Party Services, such as social media and social networking services like Facebook, Twitter and Google. Your access and use of the Third-Party Services may also be subject to additional terms and conditions, privacy policies, or other agreements with such third party, and you may be required to authenticate to or create separate accounts to use Third-Party Services on the websites or via the technology platforms of their respective providers. Some Third-Party Services will provide us with access to certain information that you have provided to third parties, including through such Third-Party Services, and we will use, store and disclose such information in accordance with our Privacy Policy. For more information about the implications of activating Third-Party Services and our use, storage and disclosure of information related to you and your use of such Third-Party Services within the Service, please see our Privacy Policy. Company has no control over and is not responsible for such Third-Party Services, including for the accuracy, availability, reliability, or completeness of information
                        shared by or available through Third-Party Services, or the privacy practices of Third-Party Services. We encourage you to review the terms of service and privacy policies of the third parties providing Third-Party Services prior to using such services. You, and not Company, will be responsible for any and all costs and charges associated with your use of any Third-Party Services. Company enables these Third-Party Services merely as a convenience and the integration or inclusion of such Third-Party Services does not imply an endorsement or recommendation. Any dealings you have with third parties while using the Services are between you and the third party. Company will not be responsible
                        or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any Third-Party Services.</p>
                    <h3 class="mb-3">Mobile Services</h3>
                    <p>The Services include certain services that are available via a mobile device, including (a) the ability to upload content to the Services via a mobile device and (b) the ability to browse the Services and the Site from a mobile device (collectively, the <strong>Mobile Services</strong>. To the extent you access the Services through a mobile device, your wireless service carriers standard charges, data rates, and other fees may apply. In addition, using certain Mobile Services may be prohibited or restricted by your carrier, and not all Mobile Services may work with all carriers or devices</p>
                    <h3 class="mb-3">Indemnity and Release</h3>
                    <p>You agree to release, indemnify and hold Company and its affiliates and their officers, employees, directors and agents (collectively, <strong>Indemnitees</strong> harmless from any from any and all losses, damages, expenses, including reasonable attorneys fees, rights, claims, actions of any kind and injury (including death) or property damage arising (directly or indirectly) out of or relating to your use of the Services, your participation in a Sweepstakes, your use or misuse of the Service Content, your violation of these Terms of Service or the Official Rules, or your violation of any rights of any third party. Company shall provide notice to you of any such claim, suit, or proceeding. Company reserves the right to assume the exclusive defense and control of any matter which is subject to indemnification under this section. In such case, you agree to cooperate with any reasonable requests assisting Companys defense of such matter. If you are a California resident, you waive California Civil Code Section 1542, which says: A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor. If you are a resident of another jurisdiction, you waive any comparable statute or doctrine to the fullest extent permitted by applicable law.</p>
                    <h3 class="mb-3">Disclaimer of Warranties</h3>
                    <p>YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. THE SERVICES ARE PROVIDED ON AN AS IS AND AS AVAILABLE BASIS. COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
                    <p>COMPANY MAKES NO WARRANTY THAT (A) THE SERVICES WILL MEET YOUR REQUIREMENTS, (B) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (C) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY SERVICES, INFORMATION, PRIZES OR OTHER MATERIAL OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS.</p>
                    <h3 class="mb-3">Limitation of Liability</h3>
                    <p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT COMPANY WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, RESULTING FROM: (A) THE USE OR THE INABILITY TO USE THE SERVICES; (B) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO THROUGH OR FROM THE SERVICES; (C) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (D) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICES; OR (E) ANY OTHER MATTER RELATING TO THE SERVICES. IN NO EVENT WILL COMPANYS TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OF ACTION EXCEED ONE HUNDRED DOLLARS ($100).</p>
                    <p>SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OR EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS SET FORTH ABOVE MAY NOT
                        APPLY TO YOU OR BE ENFORCEABLE WITH RESPECT TO YOU. IF YOU ARE DISSATISFIED WITH ANY PORTION OF THE SERVICES OR WITH THESE TERMS OF SERVICE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USE OF THE SERVICES.</p>
                    <p>IF YOU ARE A USER FROM NEW JERSEY, THE FOREGOING SECTIONS TITLED DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY ARE INTENDED TO BE ONLY AS BROAD AS IS PERMITTED UNDER THE LAWS OF THE STATE OF NEW JERSEY. IF ANY PORTION OF THESE SECTIONS IS HELD TO BE INVALID UNDER THE LAWS OF THE STATE OF NEW JERSEY, THE INVALIDITY OF SUCH PORTION SHALL NOT AFFECT THE VALIDITY OF THE REMAINING PORTIONS OF THE APPLICABLE SECTIONS.</p>
                    <h3 class="mb-3">Dispute Resolution By Binding Arbitration </h3>
                    <strong> PLEASE READ THIS SECTION CAREFULLY AS IT AFFECTS YOUR RIGHTS, SUBJECT TO APPLICABLE LAW.</strong>
                        <ol>
                            <li><strong>Agreement to Arbitrate </strong></li>
                        </ol>
                        <p>This Dispute Resolution by Binding Arbitration section is referred to in this Terms of Service as the <strong>Arbitration Agreement</strong>. You agree that to the fullest extent permitted by applicable law, any and all disputes
                            or claims that have arisen or may arise between you and Company, whether arising out of or relating to this Terms of Service (including any alleged breach thereof), the Services, any advertising, any aspect of the relationship or transactions between us, shall be resolved exclusively through final and binding arbitration, rather than a court, in accordance with the terms of this Arbitration Agreement, except that you may assert individual claims
                            in small claims court, if your claims qualify. Further, this Arbitration Agreement does not preclude you from bringing issues to the attention of federal, state, provincial/territorial, or local agencies, and such agencies can, if the law allows, seek relief against us on your behalf. You agree that, by entering into this Terms of Service, you and Company are each waiving the right to a trial by jury or to participate in a class action, to the fullest extent permitted by applicable law. Your rights will be determined by a neutral arbitrator, not a judge or jury. The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.</p>
                        <ol>
                            <li><strong>Prohibition of Class and Representative Actions and Non-Individualized Relief </strong></li>
                        </ol>
                        <p><em><strong>TO THE FULLEST EXTENT PERMITTED BY LAW, YOU AND COMPANY AGREE THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING.  UNLESS BOTH YOU AND COMPANY AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSONS OR PARTYS CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING.  ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTYS INDIVIDUAL CLAIM(S), EXCEPT THAT YOU MAY PURSUE A CLAIM FOR AND THE ARBITRATOR MAY AWARD PUBLIC INJUNCTIVE RELIEF UNDER APPLICABLE LAW TO THE EXTENT REQUIRED FOR THE ENFORCEABILITY OF THIS PROVISION. </strong></em></p>
                        <ol>
                            <li><strong>Pre-Arbitration Dispute Resolution</strong></li>
                        </ol>
                        <p>Company is always interested in resolving disputes amicably and efficiently, and most customer concerns can be resolved quickly and to the customers satisfaction by emailing customer support <a href="mailto:support@wizza.com">support@kwikisweeps.com</a>. If such efforts prove unsuccessful, a party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute <strong>Notice</strong>. The Notice to Company should be sent to 930 Washington Ave Suite 210 Miami Beach FL 33139 <strong>Notice Address</strong>. The Notice must (i) describe the nature and basis of the claim or dispute and (ii) set forth the specific relief sought. If Company and you do not resolve the claim within sixty (60) calendar days after the Notice is received, you or Company may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by Company or you shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you or Company is entitled.</p>
                        <ol>
                            <li><strong>Arbitration Procedures</strong></li>
                        </ol>
                        <p>Arbitration will be conducted by a neutral arbitrator in accordance with the American Arbitration Associations <strong>AAA</strong> rules and procedures, including the AAAs Consumer Arbitration Rules collectively, the <strong>AAA Rules</strong>, as modified by this Arbitration Agreement. For information on the AAA, please visit its website, http://www.adr.org. Information about the AAA Rules and fees for consumer disputes can be found at the AAAs consumer arbitration page, http://www.adr.org/consumer_arbitration. If there is any inconsistency between any term of the AAA Rules and any term of this Arbitration Agreement, the applicable terms of this Arbitration Agreement will control unless the arbitrator determines that the application of the inconsistent Arbitration Agreement terms would not result in a fundamentally fair arbitration. The arbitrator must also follow the provisions of these Terms of Service as a court would. All issues are for the arbitrator to decide, including, but not limited to, issues relating to the scope, enforceability, and arbitrability of this Arbitration Agreement. Although arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings, the arbitrator can award the same damages and relief on an individual basis that a court can award to an individual under the Terms of Service and applicable law. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons.</p>
                        <p>Unless Company and you agree otherwise, any arbitration hearings will take place in a reasonably convenient location for both parties with due consideration of their ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, the determination shall be made by AAA. If your claim is for USD$10,000 or less, Company agrees that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, through a telephonic hearing, or by an in-person hearing as established by the AAA Rules. If your claim exceeds USD$10,000, the right to a hearing will be determined by the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the award is based.</p>
                        <ol>
                            <li><strong>Costs of Arbitration</strong></li>
                        </ol>
                        <p>The parties will equally split the arbitrators fees, and expenses and each party shall pay its costs and attorneys fees. If you can demonstrate that the costs of arbitration will be prohibitive as compared to the costs of litigation, Company will pay as much of the claimants filing, and hearing fees in connection with the arbitration as the arbitrator deems necessary to prevent the arbitration from being cost-prohibitive. Notwithstanding, if either party prevails on a statutory claim that affords a prevailing party attorneys fees and costs, or if there is a written agreement providing for attorneys fees and costs, the arbitrator will award such costs and fees per the applicable statute or written agreement. The arbitrator shall resolve any dispute regarding the reasonableness of any fee or cost that may be awarded under this Paragraph. </p>
                        <ol>
                            <li><strong>Confidentiality</strong></li>
                        </ol>
                        <p>All aspects of the arbitration proceeding, and any ruling, decision, or award by the arbitrator, will be strictly confidential for the benefit of all parties.</p>
                        <ol>
                            <li><strong>Severability</strong></li>
                        </ol>
                        <p>If a court or the arbitrator decides that any term or provision of this Arbitration Agreement (other than the subsection (b) titled Prohibition of Class and Representative Actions and Non-Individualized Relief above where permitted by applicable law) is invalid or unenforceable, the parties agree to replace such term or provision with a term or provision that is valid and enforceable and that comes closest to expressing the intention of the invalid or unenforceable term or provision, and this Arbitration Agreement shall be enforceable as so modified. If a court or the arbitrator decides that any of the provisions of subsection (b) above titled Prohibition of Class and Representative Actions and Non-Individualized Relief are invalid or unenforceable, then the entirety of this Arbitration Agreement shall be null and void, unless such provisions are deemed to be invalid or unenforceable solely with respect to claims for public injunctive relief. The remainder of the Terms of Service will continue to apply.</p>
                        <ol>
                            <li><strong>Future Changes to Arbitration Agreement</strong></li>
                        </ol>
                        <p>Notwithstanding any provision in this Terms of Service to the contrary, Company agrees that if it makes any future change to this Arbitration Agreement (other than a change to the Notice Address) while you are a user of the Services, you may reject any such change by sending Company written notice within thirty (30) calendar days of the change to the Notice Address provided above. By rejecting any future change, you are agreeing that you will arbitrate any dispute between us in accordance with the language of this Arbitration Agreement as of the date you first accepted these Terms of Service (or accepted any subsequent changes to these Terms of Service).</p>
                        <h3 class="mb-3">Termination</h3>
                        <p>You agree that Company, in its sole discretion, may suspend or terminate your Account (or any part thereof) or use of the Services and remove and discard any content within the Services, for any reason, including, without limitation, for lack of use or if Company believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Service. Notwithstanding the foregoing, the Company may not suspend or terminate your Account during a Sweepstakes that you entered unless you have materially breached a provision of these Terms of Service or the Additional Terms and you failed to cure any such breach within thirty (30) days of your receipt of written notice of such breach from Company. Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Services, may be referred to appropriate law enforcement authorities. Company may also in its sole discretion and at any time discontinue providing the Services, or any part thereof, with or without notice. You agree that any termination of your access to the Services under any provision of this Terms of Service may be effected without prior notice (except where otherwise provided or required by applicable law), and acknowledge and agree that Company may immediately deactivate or delete your Account and all related information and files in your Account and/or bar any further access to such files or the Services. Further, you agree that Company will not be liable to you or any third party for any termination of your access to the Services.</p>
                        <h3 class="mb-3">User Disputes</h3>
                        <p>You agree that you are solely responsible for your interactions with any other user in connection with the Services and Company will have no liability or responsibility with respect thereto. Company reserves the right, but has no obligation, to become involved in any way with disputes between you and any other user of the Services.</p>
                        <h3 class="mb-3">General</h3>
                        <p>These Terms of Service constitute the entire agreement between you and Company and govern your use of the Services, superseding any prior agreements between you and Company with respect to the Services. You also may be subject to additional terms and conditions that may apply when you use affiliate or third party services, third party content or third party software. These Terms of Service will be governed by the laws of the State of New York without regard to its conflict of law provisions. With respect to any disputes or claims not subject to arbitration, as set forth above, you and Company agree to submit to the personal and exclusive jurisdiction of the state and federal courts located within New York, NY. The failure of Company to exercise or enforce any right or provision of these Terms of Service will not constitute a waiver of such right or provision. If any provision of these Terms of Service is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that such provision shall be severed from the Terms of Service and the court should endeavor to give effect to the parties intentions as reflected in the provision, and the other provisions of these Terms of Service remain in full force and effect. To the fullest extent permitted by applicable law, you agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of the Services or these Terms of Service must be filed within one (1) year after such claim or cause of action arose or be forever barred. A printed version of this agreement and of any notice given in electronic form will be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. You may not assign this Terms of Service without the prior written consent of Company, but Company may assign or transfer this Terms of Service, in whole or in part, without restriction. In addition, Company may subcontract or delegate to other parties (including affiliates) its rights and obligations under these Terms of Service, including the performance of any or all of the Services. The section titles in these Terms of Service are for convenience only and have no legal or contractual effect. Notices to you may be made via either email or regular mail. The Services may also provide notices to you of changes to these Terms of Service or other matters by displaying notices or links to notices generally on the Services.</p>
                        <h3 class="mb-3">Your Privacy</h3>
                        <p>We respect the privacy of our users. For details please see our Privacy Policy. By using the Services, you consent to our collection, use and disclosure of personal data as outlined therein.</p>
                        <h3 class="mb-3">Questions? Concerns? Suggestions?</h3>
                        <p>Please contact us at <a href="mailto:support@kwikisweeps.com">support@kwikisweeps.com</a> to report any violations of these Terms of Service or to pose any questions regarding this Terms of Service or the Services.</p>

                </div>

            </div>

        </div>

    </section>

    <!-- privacy-policy End -->

    <!-- footer-section start -->

    <?php include('assets/include/footer.php'); ?>

    <!-- Js start -->

    <?php include('assets/include/js.php'); ?>

</body>

</html>